package ru.rudrive.voyahadb;

import android.app.*; import android.os.*; import android.text.InputType; import android.view.*; import android.widget.*; import android.graphics.Color; import android.content.SharedPreferences;

public class MainActivity extends Activity implements AdbClient.Listener {
 private EditText ip,port,command; private TextView status,output,wifiInfo; private ScrollView scroll; private AdbClient adb; private NetworkScanner scanner; private SharedPreferences prefs;
 @Override public void onCreate(Bundle b){super.onCreate(b);adb=new AdbClient(this);scanner=new NetworkScanner();prefs=getSharedPreferences("voyah_adb",MODE_PRIVATE);setContentView(buildUi());}
 private View buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(10),dp(12),dp(10));root.addView(text("VOYAH ADB — IHBC / Matrix",20));status=text("Отключено",13);root.addView(status);wifiInfo=text("Wi‑Fi IP телефона: "+safe(NetworkScanner.findLocalIpv4()),12);root.addView(wifiInfo);LinearLayout conn=row();ip=edit("IP автомобиля",prefs.getString("last_ip","192.168.1.100"));ip.setInputType(InputType.TYPE_CLASS_PHONE);port=edit("Порт",prefs.getString("last_port","5555"));port.setInputType(InputType.TYPE_CLASS_NUMBER);conn.addView(ip,new LinearLayout.LayoutParams(0,dp(48),3));conn.addView(port,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(conn);LinearLayout d=row();d.addView(button("НАЙТИ VOYAH",v->discoverVoyah()),weight());d.addView(button("ПОДКЛЮЧИТЬ",v->connect()),weight());root.addView(d);LinearLayout b=row();b.addView(button("ОТКЛЮЧИТЬ",v->adb.disconnect()),weight());b.addView(button("ПОВТОРИТЬ",v->connect()),weight());root.addView(b);root.addView(text("Диагностика IHBC",15));LinearLayout q1=row();q1.addView(button("Activity",v->send("dumpsys activity activities | grep -E 'mResumedActivity|mFocusedActivity'")),weight());q1.addView(button("IHBC LOG",v->send("logcat | grep -Ei 'IHBC|MATRIXLIGHT|getSupportIHBC|isSupportIHBC|getLightIhbc|setLightIhbc|LightFragment|VehicleCanBusTool'")),weight());root.addView(q1);LinearLayout q2=row();q2.addView(button("CLEAR LOG",v->send("logcat -c")),weight());q2.addView(button("PKG PATH",v->send("pm path com.qinggan.carsignal.service")),weight());root.addView(q2);root.addView(button("CTRL + C — остановить текущую команду",v->new Thread(()->{try{adb.sendCtrlC();append("\n^C\n");}catch(Exception e){onError(e.getMessage());}}).start()),new LinearLayout.LayoutParams(-1,dp(52)));command=edit("Команда shell","getprop ro.product.board");root.addView(command,new LinearLayout.LayoutParams(-1,dp(52)));root.addView(button("ВЫПОЛНИТЬ",v->send(command.getText().toString())),new LinearLayout.LayoutParams(-1,dp(48)));LinearLayout ob=row();ob.addView(button("ОЧИСТИТЬ ЭКРАН",v->output.setText("")),weight());ob.addView(button("КОПИРОВАТЬ",v->copyOutput()),weight());root.addView(ob);output=text("",12);output.setTextIsSelectable(true);output.setTypeface(android.graphics.Typeface.MONOSPACE);output.setTextColor(Color.rgb(20,20,20));scroll=new ScrollView(this);scroll.addView(output);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));return root;}
 private void discoverVoyah(){if(scanner!=null)scanner.cancel();scanner=new NetworkScanner();wifiInfo.setText("Wi‑Fi IP телефона: "+safe(NetworkScanner.findLocalIpv4()));status.setText("Поиск ADB на Wi‑Fi…");append("\n[ПОИСК] Ищу TCP 5555 в локальной /24 сети…\n");scanner.scan5555(new NetworkScanner.Listener(){public void onProgress(String t){runOnUiThread(()->status.setText(t));}public void onFound(String f){runOnUiThread(()->{ip.setText(f);prefs.edit().putString("last_ip",f).apply();append("[НАЙДЕНО] "+f+":5555\n");connect();});}public void onFinished(boolean f){if(!f)runOnUiThread(()->{status.setText("ADB:5555 не найден");append("[ПОИСК] Устройство не найдено.\n");});}});}
 private void connect(){final String h=ip.getText().toString().trim();final int p;try{p=Integer.parseInt(port.getText().toString());}catch(Exception e){onError("Неверный порт");return;}prefs.edit().putString("last_ip",h).putString("last_port",String.valueOf(p)).apply();status.setText("Подключение…");new Thread(()->{try{adb.connect(h,p);}catch(Exception e){onError(e.getMessage());}}).start();}
 private void send(String c){if(c.trim().isEmpty())return;append("\n$ "+c+"\n");new Thread(()->{try{adb.sendCommand(c);}catch(Exception e){onError(e.getMessage());}}).start();}
 private void copyOutput(){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("Voyah ADB",output.getText()));Toast.makeText(this,"Скопировано",Toast.LENGTH_SHORT).show();}
 private void append(String s){runOnUiThread(()->{output.append(s);scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));});} public void onText(String s){append(s);} public void onState(String s){runOnUiThread(()->status.setText(s));} public void onError(String s){runOnUiThread(()->{status.setText("Ошибка");append("\n[ОШИБКА] "+s+"\n");});} @Override protected void onDestroy(){if(scanner!=null)scanner.cancel();adb.disconnect();super.onDestroy();}
 private String safe(String s){return s==null?"не определён":s;} private TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setPadding(dp(4),dp(3),dp(4),dp(3));return v;} private EditText edit(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setSingleLine(true);return e;} private Button button(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);b.setAllCaps(false);return b;} private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;} private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(48),1);} private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+0.5f);}
}
